#!/usr/bin/env python3
"""Generate the bundled C1 Package Bitmap font; Python standard library only.

Run from any directory. Normal device/host builds never run this script and
never require network access or an external font. --check verifies committed
outputs without modifying them. --source accepts an offline release archive.
The bitmap subset is distributed under SIL OFL 1.1 (see third_party/pkg_font).
"""
import argparse
import hashlib
import io
from pathlib import Path
import tarfile
import urllib.request
from concurrent.futures import ThreadPoolExecutor
import tempfile

VERSION = "16.0.04"
URL = f"https://unifoundry.com/pub/unifont/unifont-{VERSION}/unifont-{VERSION}.tar.gz"
SHA256 = "2bd4e4679757126f48e1bf2c1be40b09aa92162bfedda4683ce5fbc70a2a5972"
ROOT = Path(__file__).resolve().parents[1]
# Full CJK Unified Ideographs + Extension A, compatibility ideographs, radicals,
# Chinese punctuation, kana/bopomofo, Latin, arrows, common UI and box symbols.
RANGES = [(0x20, 0x7e), (0xa0, 0x24f), (0x2000, 0x206f),
          (0x2190, 0x21ff), (0x2500, 0x25ff), (0x2e80, 0x312f),
          (0x31a0, 0x31bf), (0x3400, 0x4dbf), (0x4e00, 0x9fff),
          (0xf900, 0xfaff), (0xff00, 0xffef), (0xfffd, 0xfffd)]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    cache = Path.home() / ".cache" / "c1pkg" / f"unifont-{VERSION}.tar.gz"
    legacy_cache = Path(tempfile.gettempdir()) / f"c1pkg-unifont-{VERSION}.tar.gz"
    if args.source:
        archive = args.source.read_bytes()
    elif cache.exists():
        archive = cache.read_bytes()
    elif legacy_cache.exists():
        archive = legacy_cache.read_bytes()
    else:
        # Independent bounded range requests avoid a single slow connection.
        # The complete archive is authenticated by the pinned SHA256 below.
        size, chunk = 32852475, 4 * 1024 * 1024
        def fetch(start):
            end = min(start + chunk, size) - 1
            request = urllib.request.Request(URL, headers={"Range": f"bytes={start}-{end}"})
            with urllib.request.urlopen(request, timeout=120) as response:
                data = response.read(end - start + 2)
                if response.status != 206 or len(data) != end - start + 1:
                    raise ValueError("upstream did not return the requested archive range")
                return data
        with ThreadPoolExecutor(max_workers=8) as pool:
            archive = b"".join(pool.map(fetch, range(0, size, chunk)))
    digest = hashlib.sha256(archive).hexdigest()
    print(f"source SHA256 {digest}", flush=True)
    if digest != SHA256:
        raise SystemExit("upstream archive checksum mismatch")
    if not args.source:
        cache.parent.mkdir(parents=True, exist_ok=True)
        cache.write_bytes(archive)
    with tarfile.open(fileobj=io.BytesIO(archive), mode="r:gz") as tar:
        members = tar.getnames()
        # Deliberately select Unicode source files, never recursively merge
        # alt/ (which includes a non-Unicode CP437 map and stylistic variants).
        source_names = ["unifont-base.hex", "wqy.hex", "spaces.hex",
                        "plane00-unassigned.hex", "plane00-nonprinting.hex"]
        glyphs = {}
        for basename in source_names:
            name = f"unifont-{VERSION}/font/plane00/{basename}"
            data = tar.extractfile(name).read().decode("ascii")
            for line in data.splitlines():
                if not line or line.startswith("#"):
                    continue
                cp, bitmap = line.split(":")
                glyphs[int(cp, 16)] = bytes.fromhex(bitmap)
        license_parts = []
        for relative in ("README", "font/plane00/README", "COPYING", "OFL-1.1.txt"):
            name = f"unifont-{VERSION}/{relative}"
            license_parts.append((name, tar.extractfile(name).read().decode("utf-8")))
        if not license_parts:
            raise SystemExit("missing upstream license")
    codepoints = [cp for first, last in RANGES for cp in range(first, last + 1)]
    missing = [cp for cp in codepoints if cp not in glyphs]
    if missing:
        raise SystemExit(f"missing glyphs: {[hex(c) for c in missing[:30]]}")
    header = ["/* Generated by tools/generate_pkg_font.py; DO NOT EDIT.",
              f" * C1 Package Bitmap: subset of GNU Unifont {VERSION}.",
              " * Font data: SIL OFL 1.1; see third_party/pkg_font/LICENSE.txt.",
              f" * Source archive SHA256: {digest}",
              " */", "#ifndef C1PKG_FONT_GENERATED_H", "#define C1PKG_FONT_GENERATED_H", "",
              "static const struct { uint32_t first, last, offset; } c1pkg_font_ranges[] = {"]
    offset = 0
    for first, last in RANGES:
        header.append(f"    {{0x{first:04x}U, 0x{last:04x}U, {offset}U}},")
        offset += last - first + 1
    header.extend(["};", "", "static const uint8_t c1pkg_font_widths[] = {"])
    widths, rows = [], []
    for cp in codepoints:
        bitmap = glyphs[cp]
        if len(bitmap) not in (16, 32):
            raise SystemExit(f"unexpected glyph dimensions: U+{cp:04X}")
        widths.append(len(bitmap) // 2)
        if len(bitmap) == 16:
            rows.append([b << 8 for b in bitmap])
        else:
            rows.append([int.from_bytes(bitmap[i:i+2], "big") for i in range(0, 32, 2)])
    for i in range(0, len(widths), 32):
        header.append("    " + ",".join(str(w) for w in widths[i:i+32]) + ",")
    header.extend(["};", "", "static const uint16_t c1pkg_font_rows[][16] = {"])
    for cp, row in zip(codepoints, rows):
        header.append("    {" + ",".join(f"0x{r:04x}" for r in row) + f"}}, /* U+{cp:04X} */")
    header.extend(["};", "", "#endif", ""])
    license_text = "C1 Package Bitmap\n=================\n\nSubset of GNU Unifont " + VERSION + ".\nFont subset/reformatting: 2026-09-06. Glyph shapes are unchanged.\nDistributed under the SIL Open Font License 1.1 option of the\nupstream dual license. The upstream notices follow verbatim.\n\n"
    for name, text in license_parts:
        license_text += f"--- {name} ---\n{text}\n"
    # Core updates carry exactly four binaries. Embed the complete notices in
    # c1pkg as well, so every OTA recipient receives the license without a
    # manifest format change or an unsigned extra file.
    notice = (license_text + "\n" + (ROOT / "third_party/pkg_font/README.md").read_text(encoding="utf-8")).encode("utf-8") + b"\0"
    license_header = ["/* Generated by tools/generate_pkg_font.py; DO NOT EDIT. */",
                      "static const unsigned char c1pkg_font_notice[] = {"]
    for i in range(0, len(notice), 24):
        license_header.append("    " + ",".join(str(b) for b in notice[i:i+24]) + ",")
    license_header.extend(["};", ""])
    outputs = {ROOT / "src/pkg/font_license_generated.h": "\n".join(license_header),
               ROOT / "src/pkg/font_generated.h": "\n".join(header),
               ROOT / "third_party/pkg_font/LICENSE.txt": license_text}
    for path, text in outputs.items():
        encoded = text.encode("utf-8")
        if args.check:
            if not path.exists() or path.read_bytes() != encoded:
                raise SystemExit(f"generated output differs: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(encoded)
    print(f"{'Verified' if args.check else 'Generated'} {len(codepoints)} glyphs, {len(codepoints)*33} bitmap/width bytes")


if __name__ == "__main__":
    main()
