"""Compile the original raw wallpaper into a self-contained C resource header.

Run only when intentionally updating the bundled default. Normal core builds
use the checked-in generated header and do not depend on external user files.
"""
from pathlib import Path
import argparse
import hashlib

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("source", type=Path)
parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[1] / "src/ui/wallpaper_default.h")
args = parser.parse_args()
data = args.source.read_bytes()
if len(data) != 296 * 152 // 8:
    parser.error("default wallpaper must be exactly 5624 bytes")
lines = [
    "/* Generated by scripts/build-wallpaper-asset.py from the original wallpaper.",
    f" * SHA-256: {hashlib.sha256(data).hexdigest()} */",
    "#ifndef C1_UI_WALLPAPER_DEFAULT_H",
    "#define C1_UI_WALLPAPER_DEFAULT_H",
    "static const uint8_t c1_wallpaper_default[] = {",
]
for start in range(0, len(data), 16):
    lines.append("    " + ", ".join(f"0x{value:02x}U" for value in data[start:start + 16]) + ",")
lines += ["};", "_Static_assert(sizeof(c1_wallpaper_default) == C1_DISPLAY_FRAME_BYTES,", '               "default wallpaper frame size");', "#endif", ""]
args.output.write_text("\n".join(lines), encoding="ascii")
print(f"Compiled original wallpaper resource: {len(data)} bytes, SHA-256 {hashlib.sha256(data).hexdigest()}")
